import cv2
imagem = cv2.imread("C:\\Users\\LABIC\\Desktop\\Yosef Lab\\LAPISCO-TASKS-1\\TASK-5\\arara.jpg")
cv2.imshow("Arara: ", imagem)
imagem_cinza = cv2.cvtColor(imagem,cv2.COLOR_BGR2GRAY)
cv2.imshow("Arara cinza: ", imagem_cinza)
imagem_media = cv2.blur(imagem_cinza, (7,7))
imagem_mediana = cv2.medianBlur(imagem_cinza, 7)
cv2.imshow("Media: ", imagem_media)
cv2.imshow("Mediana: ", imagem_mediana)
cv2.imwrite("Media.jpg", imagem_media)
cv2.imwrite("Mediana.jpg", imagem_mediana)
cv2.waitKey(0)
cv2.destroyAllWindows()