import cv2
imagem = cv2.imread("C:\\Users\\LABIC\\Desktop\\Yosef Lab\\LAPISCO-TASKS-1\\TASK-8\\paisagem.jpg")
imagem_cinza = cv2.cvtColor(imagem,cv2.COLOR_BGR2GRAY)
cv2.imshow("Paisagem Cinza: ", imagem_cinza)
imagem_reduzida = cv2.resize(imagem_cinza, (160,120), interpolation= cv2.INTER_AREA)
imagem_aumentada = cv2.resize(imagem_cinza, (640,480), interpolation= cv2.INTER_CUBIC)
cv2.imshow("Imagem Reduizada: ", imagem_reduzida)
cv2.imshow("Imagem Aumentada: ", imagem_aumentada)
cv2.imwrite("Reduizada.jpg", imagem_reduzida)
cv2.imwrite("Aumentada.jpg", imagem_aumentada)
cv2.waitKey(0)
cv2.destroyAllWindows()